Added LOGICAL_SIZE measurement
valiton/grafana-mongodb-atlas-datasource pull request #33
Opened 2021-02-17 14:19 UTC by wywywywy

Missing LOGICAL_SIZE measurement as mentioned in issue #32

2021-02-17 17:34 UTC, CapChrisCap requested changes
Awesome, thanks for the MR. Can you please fix the minor changes? Then we can merge your change! 👍

2021-02-17 17:34 UTC, CapChrisCap commented on src/query_parameter_ctrl.ts
> +        $scope.target.dimensionName
Can you please remove the formatting?

2021-02-17 17:34 UTC, CapChrisCap commented on src/query_parameter_ctrl.ts
> +      $scope.onChange = () => { };
Can you please remove the formatting?

2021-02-17 17:56 UTC, wywywywy commented
Sorry not sure what happened there.  I didn't think I had auto-formatting switched on.

Anyway, new commit done.

2021-02-18 14:12 UTC, merged

2021-02-19 09:36 UTC, wywywywy commented
The updated instruction has a problem.

The **;mongodb-atlas-datasource** part is missing.

`-e GF_INSTALL_PLUGINS="https://github.com/valiton/grafana-mongodb-atlas-datasource/releases/download/v2.0.0/mongodb-atlas-datasource.zip;mongodb-atlas-datasource"`

2021-02-19 10:34 UTC, CapChrisCap commented
Thanks for mentioning this! Directly fixed the README.